export const NYC_NEIGHBORHOODS = {
  Manhattan: [
    'Upper East Side',
    'Upper West Side',
    'Harlem',
    'East Harlem',
    'Morningside Heights',
    'Washington Heights',
    'Inwood',
    'Midtown East',
    'Midtown West',
    'Hell\'s Kitchen',
    'Chelsea',
    'Greenwich Village',
    'East Village',
    'West Village',
    'SoHo',
    'Nolita',
    'Lower East Side',
    'Chinatown',
    'Little Italy',
    'Tribeca',
    'Financial District',
    'Battery Park City',
    'Murray Hill',
    'Gramercy',
    'Stuyvesant Town',
    'Kips Bay',
    'Flatiron',
    'NoHo',
    'Bowery',
  ],
  Queens: [
    'Astoria',
    'Long Island City',
    'Sunnyside',
    'Woodside',
    'Jackson Heights',
    'Elmhurst',
    'Corona',
    'Flushing',
    'Forest Hills',
    'Rego Park',
    'Kew Gardens',
    'Richmond Hill',
    'Ozone Park',
    'Howard Beach',
    'Jamaica',
    'Queens Village',
    'Bayside',
    'Little Neck',
    'Douglaston',
    'Fresh Meadows',
    'Kew Gardens Hills',
    'Briarwood',
    'Jamaica Estates',
    'St. Albans',
    'Cambria Heights',
    'Laurelton',
    'Rosedale',
    'Far Rockaway',
    'Rockaway Beach',
    'Arverne',
    'Belle Harbor',
    'Broad Channel',
  ],
  Brooklyn: [
    'Williamsburg',
    'Greenpoint',
    'DUMBO',
    'Brooklyn Heights',
    'Downtown Brooklyn',
    'Boerum Hill',
    'Cobble Hill',
    'Carroll Gardens',
    'Red Hook',
    'Park Slope',
    'Prospect Heights',
    'Fort Greene',
    'Clinton Hill',
    'Bedford-Stuyvesant',
    'Crown Heights',
    'Prospect-Lefferts Gardens',
    'Flatbush',
    'Ditmas Park',
    'Kensington',
    'Windsor Terrace',
    'Gowanus',
    'Sunset Park',
    'Bay Ridge',
    'Dyker Heights',
    'Bensonhurst',
    'Borough Park',
    'Gravesend',
    'Coney Island',
    'Brighton Beach',
    'Sheepshead Bay',
    'Manhattan Beach',
    'Marine Park',
    'Mill Basin',
    'Bergen Beach',
    'Canarsie',
    'East Flatbush',
    'Brownsville',
    'East New York',
    'Bushwick',
    'East Williamsburg',
  ],
  Bronx: [
    'Riverdale',
    'Spuyten Duyvil',
    'Kingsbridge',
    'Fordham',
    'University Heights',
    'Morris Heights',
    'Highbridge',
    'Concourse',
    'Mott Haven',
    'Port Morris',
    'Melrose',
    'Longwood',
    'Hunts Point',
    'Soundview',
    'Parkchester',
    'Westchester Square',
    'Pelham Bay',
    'City Island',
    'Co-op City',
    'Pelham Parkway',
    'Van Cortlandt Village',
    'Wakefield',
    'Eastchester',
    'Baychester',
    'Williamsbridge',
    'Norwood',
    'Bedford Park',
    'Belmont',
    'Allerton',
    'Woodlawn Heights',
    'Bronx Park',
    'Tremont',
    'Concourse Village',
  ],
  'Staten Island': [
    'St. George',
    'New Brighton',
    'Stapleton',
    'Tompkinsville',
    'Port Richmond',
    'West Brighton',
    'Grymes Hill',
    'Clifton',
    'Rosebank',
    'Dongan Hills',
    'Grant City',
    'New Dorp',
    'Todt Hill',
    'Richmondtown',
    'Eltingville',
    'Annadale',
    'Great Kills',
    'Oakwood',
    'Bay Terrace',
    'New Springville',
    'Travis',
    'Tottenville',
    'Rossville',
    'Prince\'s Bay',
    'Huguenot',
    'Arrochar',
    'South Beach',
    'Midland Beach',
    'Fort Wadsworth',
    'Shore Acres',
  ],
} as const;

export type Borough = keyof typeof NYC_NEIGHBORHOODS;

export const ALL_NEIGHBORHOODS: string[] = [
  ...NYC_NEIGHBORHOODS.Manhattan.map(n => `Manhattan - ${n}`),
  ...NYC_NEIGHBORHOODS.Queens.map(n => `Queens - ${n}`),
  ...NYC_NEIGHBORHOODS.Brooklyn.map(n => `Brooklyn - ${n}`),
  ...NYC_NEIGHBORHOODS.Bronx.map(n => `Bronx - ${n}`),
  ...NYC_NEIGHBORHOODS['Staten Island'].map(n => `Staten Island - ${n}`),
];
